### ISSUE TITLE
Food

### ISSUE THREAD

**Issue by yokolet** [clojurebridge-durham/organizing#4]
- Friday evening pizza or dinner
- Saturday breakfast, lunch, clojure cookie?

**Comment by yokolet** [comment]
@kfoster32 will help this. Thanks!

**Comment by yokolet** [comment]
@bridgethillyer do you think we still have time to order Clojure cookie? If so, where did you order last year?
In any case, we should have some sort of sweets for Saturday afternoon. If someone has ideas, please write here. Maybe, @jgkite knows well? Also, @kfoster32 ?

**Comment by bridgethillyer** [comment]
Mad Hatter. If you get the order in on Wed, I bet they can do them for you. They were kinda expensive.

**Comment by yokolet** [comment]
@bridgethillyer seriously... hmm..

**Comment by kfoster32** [comment]
@yokolet @bridgethillyer I was planning on ordering pizza for Friday dinner and probably Foster's Market for lunch. I will bring in things for breakfast on Saturday. Did we ask for dietary restrictions at registration?

**Comment by yokolet** [comment]
@kfoster32 The registration form does have a dietary restriction field. I have all, so will share with you.

**Comment by yokolet** [comment]
For record, @kfoster32 ordered a cake which will have Clojure logo on it. Thanks!

**Comment by yokolet** [comment]
Many thank you to @kfoster32 ! Student retro said food was good.
