### ISSUE TITLE
Stickers, brochures, give aways

### ISSUE THREAD

**Issue by yokolet** [clojurebridge-durham/organizing#7]
If there's any.

At least, we want stickers to award attendees who successfully finished installation on Friday.

**Comment by yokolet** [comment]
Bridget gave me one bunch of ClojureBridge stickers. We got enough number of stickers to give one to each student as a proof of installation completion.

**Comment by yokolet** [comment]
@lynngrogan Last year, we got some "Clojure Cookbook" from O'Reilly for give aways. Is there any possibility we can get such books, for example Carin's book? She is an instructor in our workshop.

**Comment by bridgethillyer** [comment]
AFAIK, ClojureBridge is partners with O'Reilly. But the page where you signed up to get books does not seem to be there anymore:

http://www.oreilly.com/event-sponsor/

So maybe someone just needs to fill out the new partner form?

I could have sworn this was in the Cookbook, but I can't find it there. I probably meant to put it there but never got around to it.

They will send 10 books per workshop, and I know other workshops have been doing this. You need to include the logo in the Event page and mention them as a sponsor:
http://www.oreilly.com/about/logos/index.html

**Comment by yokolet** [comment]
@bridgethillyer seriously. I firstly learned this or I totally forgot. It was more than a year ago.
I'll go that event sponsor web page and sign up. If it needs as ClojueBridge as an organization, I'll bring the topic at this Friday board meeting.
Thanks for the info. I'm really lucky, you are here :smiley:

**Comment by yokolet** [comment]
I submit the form and am waiting their response.

**Comment by yokolet** [comment]
O'Reilly got back to me. But, I don't see '10 copies of free books' in any docs:
- [Summary](https://github.com/clojurebridge-durham/organizing/blob/master/etc/O'ReillyPartnerCenterSummary.pdf)
- [Your Benefits](https://github.com/clojurebridge-durham/organizing/blob/master/etc/O'ReillyPartnerCenterBenefits.pdf)
- [Submit Deliveables](https://github.com/clojurebridge-durham/organizing/blob/master/etc/O'ReillyPartnerCenterDeliverables.pdf)

Did they changed?  or did I make wrong request?

**Comment by bridgethillyer** [comment]
It looks like it changed. The partnership does not seem worth it without the free books for workshops. Other more recent workshops have gotten the free books, though, so maybe ask them how they did it? Any of the ones that have O'Reilly as a sponsor would work - maybe ask Nola.

**Comment by yokolet** [comment]
I'll ask Nola first. Then, perhaps, others at ML.

**Comment by yokolet** [comment]
Nola said "Bridget worked out with O'Reilly on the books and had them shipped to me." Austin workshop happened March 13-14, 2015, so I guess the request was made within a year since Bridget applied to the partnership.

**Comment by yokolet** [comment]
@puredanger is helping me on give away books. I'm confident we can get some.

**Comment by yokolet** [comment]
As for give away books, things are settling down. For reasons, I left the record in ClojureBridge Durham ML, https://groups.google.com/forum/#!topic/clojurebridge-durham/mBFOTjZKhdA

**Comment by yokolet** [comment]
Still not clear how to use O'Reilly's partner program ebook coupons. Will figure out and distribute it if possible.
